[project]
name = "stocks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Mykyta Prokaiev", email = "mykytaprokaiev@gmail.com" }]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
stocks = "stocks.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
